{
    'name': 'Car dealership',
    'version': '1.0.0',
    'summary': 'Summery',
    'description': 'Description',
    'category': 'base',
    'author': 'Author',
    'website': 'Website',
    'license': '',
    'depends': ['base'],
    'data': [
        'views/vehicle_view.xml',
        'views/inventory_view.xml',
        'views/factory_view.xml',
        'views/purchase_view.xml',
        'views/client_view.xml',
        'views/contract_view.xml',
        'views/sales_view.xml',
        'views/salesperson_view.xml',
        'views/payment_view.xml',
        'views/staff_view.xml',
        'wizard/purchase_wizard.xml',
        'wizard/sale_wizard.xml',
        'wizard/purchase_report.xml',
        'wizard/sale_report.xml',
        'report/purchase_report.xml',
        'report/sale_report.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True
}
